name: don3txt
description: "Todo.txt task manager for Android"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.0
  path_provider: ^2.1.0
  google_fonts: ^8.0.2
  shared_preferences: ^2.2.0
  file_picker: ^10.3.10
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
